### PR TITLE
Initial Scaffolding

### PR DESCRIPTION
**Pull request by jameslovato**
https://www.drupal.org/project/patternkit/issues/2945643

### CODE REVIEW

**Comment by cybtachyon** [comment]
This looks like a great start. I'll go ahead and get the d.o issue updated and get this in as a base 8.x-1.x branch.

**Comment by cybtachyon** [comment]
@jameslovato Make sure to keep your Drupal.org profile updated with the same email as Github so that your commits are properly credited: https://www.drupal.org/node/2940647/committers

Thanks again for the effort!

**Comment by jameslovato** [comment]
Hello Derek,

Thanks for letting me know something was amiss. I have used the same email for both GitHub and Drupal. I cannot seem to find out why it is not working correctly.

GitHub account:
[cid:image001.png@01D3BAA0.673E5BB0]

From inside the project I committed from:

[cid:image002.png@01D3BAA0.673E5BB0]

Drupal account:
[cid:image003.png@01D3BAA0.673E5BB0]

I will continue to research why it is not crediting my account properly.

Thanks,
James

James Lovato
Web developer
www.WaterMatters.org<http://www.watermatters.org/>
Southwest Florida Water Management District
(352) 796-7211, ext. 4777

**Comment by jameslovato** [comment]
Hey Derek,

I asked Damien McKenna about this problem and he said, “That's the problem with doing Drupal contrib work on github - it doesn't work with the Drupal issue queues so you don't get attribution.”
So, I guess that was expected? Not sure if there is anything to do about it now.

I did want to say I really appreciate you for helping me through the process. It was great to work with you and was good to have that opportunity to do some coding. I unfortunately don’t get to do a lot of coding in my current position.

Thanks,
James

James Lovato
Web developer
www.WaterMatters.org<http://www.watermatters.org/>
Southwest Florida Water Management District
(352) 796-7211, ext. 4777

**Comment by cybtachyon** [comment]
Interesting. I guess you'll receive credit when we close out the D8 issue in the queue.

Thanks again!

**Pull request merged**
